version: '3.8'

services:

  app:
    build: .
    container_name: microservicio-devops

    ports:
      - "5000:5000"

    environment:
      - APP_ENV=production

    networks:
      - devops-network

    restart: always

  redis:
    image: redis:latest

    container_name: redis-cache

    networks:
      - devops-network

    restart: always

networks:
  devops-network:
