version: '3.8'

services:

  app:
    build: .
    container_name: microservicio-devops

    ports:
      - "5000:5000"

    environment:
      - APP_ENV=production

    depends_on:
      - redis

    healthcheck:
      test: ["CMD", "python", "-c", "print('ok')"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - devops-network

    restart: always

  redis:
    image: redis:latest

    container_name: redis-cache

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - devops-network

    restart: always

networks:
  devops-network:

volumes:
  redis-data:
